version: '2.12'

services:
  shorturl-node:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      - redis
      - postgres 
  redis:
    image: redis
    build:
      dockerfile: ./docker/redis/Dockerfile
    ports:
      - 6379:6379
  postgres:
     image: postgres
     build:
       dockerfile: ./docker/postgres/Dockerfile
     ports:
       - 5432:5432
